import { useRef, useEffect, useState, useCallback } from 'react'
import { createPortal } from 'react-dom'
import * as d3 from 'd3'
import { motion, AnimatePresence } from 'framer-motion'
import { Info, Maximize2, X, TrendingUp, TrendingDown, Minus } from 'lucide-react'
import { useSimulationStore } from '@/stores/simulationStore'
import { METRIC_CONFIGS, type MetricConfig } from '@/utils/metricsUtils'
import type { MetricsSnapshot } from '@/types/city.types'

const CATEGORIES = ['mobility', 'economy', 'environment', 'social', 'infrastructure'] as const
type Category = typeof CATEGORIES[number]

const CATEGORY_COLORS: Record<Category, string> = {
  mobility: '#1A6FA3',
  economy: '#B7770D',
  environment: '#1E8449',
  social: '#7D3C98',
  infrastructure: '#0097A7',
}

const METRIC_DESCRIPTIONS: Partial<Record<string, string>> = {
  pop_total: 'Total population living within the city bounds. Growth reflects residential zone placement and economic conditions.',
  pop_density_avg: 'Average number of residents per square kilometre. Higher density often correlates with efficient land use.',
  pop_growth_rate: 'Year-over-year population growth as a percentage. Healthy cities typically sustain 1–3% annual growth.',
  mobility_commute: 'Average daily commute time in minutes. Lower values indicate good transit connectivity and mixed-use zoning.',
  mobility_congestion: 'Estimated congestion pressure from growth, commute demand, and transit availability.',
  mobility_transit_coverage: 'Share of population within walking distance of a transit stop. Target is 80%+ for urban cores.',
  mobility_walkability: 'Composite walk score (0–100) based on proximity to amenities, sidewalk quality, and density.',
  econ_housing_afford: 'Housing affordability index (0–100). Higher values mean more residents can afford local housing.',
  econ_jobs_created: 'Cumulative jobs generated by commercial, industrial, and civic zone placements.',
  env_green_ratio: 'Percentage of city area covered by parks, forests, and open green space.',
  env_co2_est: 'Estimated annual CO₂ emissions in kilotonnes, derived from transport, energy, and industrial activity.',
  env_flood_exposure: 'Share of developed land in flood-risk zones. Lower is better; mitigated by green buffers and drainage.',
  equity_hosp_coverage: 'Percentage of population within acceptable distance of a hospital or health facility.',
  equity_school_access: 'Percentage of school-age residents within walking or transit distance of an educational institution.',
  infra_power_load: 'Current electricity grid load as a percentage of total capacity. Above 85% risks brownouts.',
  infra_water_capacity: 'Remaining water system capacity as a percentage. Declines as population grows without infrastructure investment.',
  safety_response_time: 'Average emergency service response time in minutes. Below 8 min is considered excellent.',
}

const PLANNING_INSIGHTS: Partial<Record<string, string>> = {
  pop_total: 'Add residential zones in transit corridors to accelerate growth while containing sprawl.',
  mobility_commute: 'Place bus stations and metro hubs within 500m of major residential clusters to cut commute times.',
  mobility_congestion: 'Mixed-use zoning reduces car trips; combine with smart traffic infrastructure for best results.',
  env_green_ratio: 'Aim for 15–20% green coverage. Distribute parks evenly to maximise walkability benefits.',
  env_co2_est: 'Each transit hub added reduces CO₂ by reducing car dependency across its catchment area.',
  econ_housing_afford: 'Low-density residential over-concentration inflates land values; introduce mid-rise mixed-use zones.',
  infra_power_load: 'Add utility zones before load exceeds 80% to avoid cascading infrastructure penalties.',
  equity_hosp_coverage: 'One hospital serves roughly 50,000 residents; plan additional facilities as population passes each threshold.',
}

function computeHealth(m: MetricsSnapshot): number {
  const scores = [
    m.equity_hosp_coverage,
    m.equity_school_access,
    m.mobility_transit_coverage,
    100 - m.mobility_congestion,
    Math.min(100, m.env_green_ratio * 2.5),
    m.mobility_walkability,
    100 - Math.min(100, m.safety_response_time * 5),
  ]
  return scores.reduce((a, b) => a + b, 0) / scores.length
}

// ─── Tiny sparkline used inside each MetricRow ──────────────────────────────

interface SparklineProps {
  history: MetricsSnapshot[]
  config: MetricConfig
  color: string
  height?: number
}

function Sparkline({ history, config, color, height = 28 }: SparklineProps) {
  const svgRef = useRef<SVGSVGElement>(null)

  useEffect(() => {
    if (!svgRef.current || history.length < 2) return
    const el = svgRef.current
    const width = el.clientWidth || 80
    const svg = d3.select(el)
    svg.selectAll('*').remove()

    const values = history.map((m) => m[config.key] as number)
    const minV = d3.min(values) ?? config.min
    const maxV = d3.max(values) ?? config.max
    const pad = (maxV - minV) * 0.1 || 1

    const x = d3.scaleLinear().domain([0, history.length - 1]).range([2, width - 2])
    const y = d3.scaleLinear().domain([minV - pad, maxV + pad]).range([height - 2, 2])

    const line = d3.line<MetricsSnapshot>()
      .x((_, i) => x(i))
      .y((d) => y(d[config.key] as number))
      .curve(d3.curveCatmullRom)

    // Area fill
    const area = d3.area<MetricsSnapshot>()
      .x((_, i) => x(i))
      .y0(height - 2)
      .y1((d) => y(d[config.key] as number))
      .curve(d3.curveCatmullRom)

    svg.append('path').datum(history).attr('fill', color).attr('opacity', 0.12).attr('d', area)
    svg.append('path').datum(history).attr('fill', 'none').attr('stroke', color)
      .attr('stroke-width', 1.5).attr('opacity', 0.9).attr('d', line)
      .style('filter', `drop-shadow(0 0 2px ${color})`)

    // Last dot
    const last = history[history.length - 1]
    svg.append('circle').attr('cx', x(history.length - 1)).attr('cy', y(last[config.key] as number))
      .attr('r', 2).attr('fill', color)
  }, [history, config, color, height])

  return <svg ref={svgRef} className="w-full" height={height} style={{ overflow: 'visible' }} />
}

// ─── Full chart used inside the expanded modal ───────────────────────────────

interface FullChartProps {
  history: MetricsSnapshot[]
  config: MetricConfig
  color: string
}

function FullChart({ history, config, color }: FullChartProps) {
  const svgRef = useRef<SVGSVGElement>(null)
  const containerRef = useRef<HTMLDivElement>(null)
  const [tooltip, setTooltip] = useState<{ x: number; y: number; value: number; year: number } | null>(null)

  useEffect(() => {
    if (!svgRef.current || !containerRef.current || history.length < 2) return
    const el = svgRef.current
    const width = el.clientWidth || 340
    const height = 180
    const margin = { top: 12, right: 16, bottom: 28, left: 52 }
    const innerW = width - margin.left - margin.right
    const innerH = height - margin.top - margin.bottom

    const svg = d3.select(el)
    svg.selectAll('*').remove()

    const values = history.map((m) => m[config.key] as number)
    const rawMin = d3.min(values) ?? config.min
    const rawMax = d3.max(values) ?? config.max
    const pad = (rawMax - rawMin) * 0.12 || 1
    const domMin = Math.max(config.min, rawMin - pad)
    const domMax = Math.min(config.max, rawMax + pad)

    const xScale = d3.scaleLinear().domain([0, history.length - 1]).range([0, innerW])
    const yScale = d3.scaleLinear().domain([domMin, domMax]).range([innerH, 0])

    const g = svg.append('g').attr('transform', `translate(${margin.left},${margin.top})`)

    // Grid lines
    g.selectAll('.grid-h')
      .data(yScale.ticks(5))
      .enter().append('line')
      .attr('x1', 0).attr('x2', innerW)
      .attr('y1', (d) => yScale(d)).attr('y2', (d) => yScale(d))
      .attr('stroke', 'var(--chart-grid)').attr('stroke-width', 0.5)

    // Area
    const area = d3.area<MetricsSnapshot>()
      .x((_, i) => xScale(i)).y0(innerH).y1((d) => yScale(d[config.key] as number)).curve(d3.curveCatmullRom)
    g.append('path').datum(history).attr('fill', color).attr('opacity', 0.1).attr('d', area)

    // Line
    const line = d3.line<MetricsSnapshot>()
      .x((_, i) => xScale(i)).y((d) => yScale(d[config.key] as number)).curve(d3.curveCatmullRom)
    g.append('path').datum(history).attr('fill', 'none').attr('stroke', color)
      .attr('stroke-width', 2).attr('opacity', 0.95).attr('d', line)
      .style('filter', `drop-shadow(0 0 3px ${color})`)

    // Data dots (small)
    g.selectAll('.dot').data(history).enter().append('circle')
      .attr('cx', (_, i) => xScale(i)).attr('cy', (d) => yScale(d[config.key] as number))
      .attr('r', 2.5).attr('fill', color).attr('opacity', 0.7)

    // Y axis
    g.append('g')
      .call(d3.axisLeft(yScale).ticks(5).tickFormat((d) => {
        const v = d as number
        if (config.max >= 1_000_000) return v >= 1e6 ? `${(v / 1e6).toFixed(1)}M` : v >= 1e3 ? `${(v / 1e3).toFixed(0)}K` : `${v}`
        if (config.max >= 1000) return v >= 1e3 ? `${(v / 1e3).toFixed(0)}K` : `${v}`
        return `${v.toFixed(0)}`
      }))
      .call((ax) => ax.select('.domain').remove())
      .call((ax) => ax.selectAll('line').remove())
      .call((ax) => ax.selectAll('text').attr('fill', 'var(--color-text-muted)').style('font-size', '9px').style('font-family', 'JetBrains Mono'))

    // X axis
    g.append('g').attr('transform', `translate(0,${innerH})`)
      .call(d3.axisBottom(xScale).ticks(Math.min(history.length - 1, 6)).tickFormat((d) => {
        const snap = history[d as number]
        return snap ? `Y${snap.year}` : ''
      }))
      .call((ax) => ax.select('.domain').remove())
      .call((ax) => ax.selectAll('line').remove())
      .call((ax) => ax.selectAll('text').attr('fill', 'var(--color-text-muted)').style('font-size', '9px').style('font-family', 'JetBrains Mono'))

    // Transparent overlay for tooltip
    g.append('rect')
      .attr('width', innerW).attr('height', innerH).attr('fill', 'transparent')
      .on('mousemove', function (event) {
        const [mx] = d3.pointer(event)
        const idx = Math.round(xScale.invert(mx))
        const clamped = Math.max(0, Math.min(history.length - 1, idx))
        const snap = history[clamped]
        if (!snap) return
        const cx = xScale(clamped) + margin.left
        const cy = yScale(snap[config.key] as number) + margin.top
        const rect = containerRef.current!.getBoundingClientRect()
        setTooltip({ x: cx, y: cy, value: snap[config.key] as number, year: snap.year })
      })
      .on('mouseleave', () => setTooltip(null))
  }, [history, config, color])

  return (
    <div ref={containerRef} style={{ position: 'relative' }}>
      <svg ref={svgRef} className="w-full" height={210} />
      <AnimatePresence>
        {tooltip && (
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.9 }}
            transition={{ duration: 0.1 }}
            style={{
              position: 'absolute',
              left: tooltip.x + 8,
              top: tooltip.y - 28,
              pointerEvents: 'none',
              background: 'var(--color-bg-panel)',
              border: `1px solid ${color}50`,
              borderRadius: 6,
              padding: '4px 8px',
              zIndex: 20,
              boxShadow: 'var(--shadow-sm)',
            }}
          >
            <div style={{ fontFamily: 'var(--font-mono)', fontSize: 9, color: 'var(--color-text-muted)', letterSpacing: '0.1em' }}>
              YEAR {tooltip.year}
            </div>
            <div style={{ fontFamily: 'var(--font-mono)', fontSize: 12, color, fontWeight: 700 }}>
              {config.format(tooltip.value)}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}

// ─── Expanded modal ──────────────────────────────────────────────────────────

interface ExpandedModalProps {
  config: MetricConfig
  history: MetricsSnapshot[]
  color: string
  onClose: () => void
}

function ExpandedModal({ config, history, color, onClose }: ExpandedModalProps) {
  const current = history.at(-1)
  const start = history[0]
  const currentVal = current ? (current[config.key] as number) : null
  const startVal = start ? (start[config.key] as number) : null
  const delta = currentVal !== null && startVal !== null ? currentVal - startVal : null
  const pctChange = delta !== null && startVal !== null && startVal !== 0
    ? (delta / Math.abs(startVal)) * 100
    : null

  const trendPositive = delta !== null ? (config.higherIsBetter ? delta > 0 : delta < 0) : null
  const TrendIcon = delta === null || Math.abs(delta) < 0.001 ? Minus : delta > 0 ? TrendingUp : TrendingDown
  const trendColor = trendPositive === null ? 'var(--color-text-muted)' : trendPositive ? 'var(--color-accent-green)' : 'var(--color-accent-danger)'

  const description = METRIC_DESCRIPTIONS[String(config.key)] ?? `${config.label} tracks city performance in the ${config.category} category.`
  const insight = PLANNING_INSIGHTS[String(config.key)] ?? `Monitor ${config.label} over time and adjust zone placements to maintain reliable service levels.`

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-50 flex items-center justify-center"
      style={{ background: 'rgba(150,155,165,0.35)', backdropFilter: 'blur(4px)' }}
      onClick={onClose}
    >
      <motion.div
        initial={{ opacity: 0, scale: 0.94, y: 12 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.94, y: 12 }}
        transition={{ duration: 0.2, ease: [0.16, 1, 0.3, 1] }}
        className="flex flex-col"
        style={{
          width: 520,
          maxWidth: '95vw',
          maxHeight: '90vh',
          background: 'var(--color-bg-panel)',
          border: `1px solid var(--color-border-subtle)`,
          borderRadius: 16,
          boxShadow: 'var(--shadow-lg)',
          overflow: 'hidden',
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div
          className="flex items-center justify-between px-5 py-4 shrink-0"
          style={{ borderBottom: `1px solid ${color}20` }}
        >
          <div className="flex items-center gap-3">
            <div
              className="w-1 h-5 rounded-full"
              style={{ background: color, boxShadow: `0 0 8px ${color}` }}
            />
            <div>
              <div className="font-display font-semibold text-sm" style={{ color: 'var(--color-text-primary)' }}>
                {config.label}
              </div>
              <div className="font-mono text-[10px] tracking-widest uppercase mt-0.5" style={{ color: 'var(--color-text-muted)' }}>
                {config.category} · {config.unit || 'index'}
              </div>
            </div>
          </div>
          <button
            onClick={onClose}
            className="w-7 h-7 flex items-center justify-center rounded-lg transition-colors"
            style={{ border: '1px solid var(--color-border-subtle)', color: 'var(--color-text-muted)', background: 'var(--color-bg-panel)', boxShadow: 'var(--shadow-sm)' }}
          >
            <X size={13} />
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto p-5 space-y-5">
          {/* Stats row */}
          <div className="grid grid-cols-3 gap-3">
            {[
              { label: 'Current', value: currentVal !== null ? config.format(currentVal) : '—' },
              { label: 'Start', value: startVal !== null ? config.format(startVal) : '—' },
              {
                label: 'Change',
                value: pctChange !== null
                  ? `${pctChange > 0 ? '+' : ''}${pctChange.toFixed(1)}%`
                  : '—',
                color: trendColor,
              },
            ].map(({ label, value, color: c }) => (
              <div
                key={label}
                className="rounded-lg p-3 text-center"
                style={{ background: 'var(--color-bg-hover)', border: '1px solid var(--color-border-subtle)', boxShadow: 'var(--shadow-inset)' }}
              >
                <div
                  className="font-mono font-bold text-lg"
                  style={{ color: c ?? color }}
                >
                  {value}
                </div>
                <div
                  className="font-mono text-[9px] tracking-widest uppercase mt-0.5"
                  style={{ color: 'var(--color-text-muted)' }}
                >
                  {label}
                </div>
              </div>
            ))}
          </div>

          {/* Trend summary */}
          <div
            className="flex items-center gap-2 px-3 py-2 rounded-lg"
            style={{ background: `${trendColor}10`, border: `1px solid ${trendColor}25` }}
          >
            <TrendIcon size={13} style={{ color: trendColor, flexShrink: 0 }} />
            <span className="font-mono text-[10px]" style={{ color: trendColor }}>
              {trendPositive === null
                ? 'No change detected yet'
                : trendPositive
                ? `${config.label} is trending in a positive direction`
                : `${config.label} is trending unfavourably — consider interventions`}
              {delta !== null && Math.abs(delta) > 0.001
                ? ` (${delta > 0 ? '+' : ''}${config.format(delta)} since start)`
                : ''}
            </span>
          </div>

          {/* Chart */}
          {history.length >= 2 ? (
            <div>
              <div
                className="font-mono text-[9px] tracking-widest uppercase mb-2"
                style={{ color: 'var(--color-text-muted)' }}
              >
                Historical Trend
              </div>
              <div
                className="rounded-lg p-2"
                style={{ background: 'var(--color-bg-hover)', border: '1px solid var(--color-border-subtle)', boxShadow: 'var(--shadow-inset)' }}
              >
                <FullChart history={history} config={config} color={color} />
              </div>
            </div>
          ) : (
            <div
              className="text-center py-8 rounded-lg font-mono text-[10px] tracking-widest uppercase"
              style={{ background: 'var(--color-bg-hover)', border: '1px solid var(--color-border-subtle)', color: 'var(--color-text-muted)', boxShadow: 'var(--shadow-inset)' }}
            >
              Run simulation to populate chart
            </div>
          )}

          {/* Description */}
          <div className="space-y-2">
            <div
              className="font-mono text-[9px] tracking-widest uppercase"
              style={{ color: 'var(--color-text-muted)' }}
            >
              What This Measures
            </div>
            <p className="text-[11px] leading-relaxed" style={{ color: 'var(--color-text-secondary)' }}>
              {description}
            </p>
          </div>

          {/* Planning insight */}
          <div
            className="rounded-lg p-3 space-y-1"
            style={{ background: `${color}08`, border: `1px solid ${color}20` }}
          >
            <div
              className="font-mono text-[9px] tracking-widest uppercase"
              style={{ color: `${color}` }}
            >
              Planning Insight
            </div>
            <p className="text-[11px] leading-relaxed" style={{ color: 'var(--color-text-secondary)' }}>
              {insight}
            </p>
          </div>
        </div>
      </motion.div>
    </motion.div>
  )
}

// ─── MetricRow with sparkline + expand button ────────────────────────────────

interface MetricRowProps {
  config: MetricConfig
  metrics: MetricsSnapshot
  history: MetricsSnapshot[]
  color: string
  onExpand: () => void
}

function MetricRow({ config, metrics, history, color, onExpand }: MetricRowProps) {
  const value = metrics[config.key] as number
  const pct = Math.max(0, Math.min(100, ((value - config.min) / (config.max - config.min)) * 100))
  const isGood = config.higherIsBetter ? pct > 60 : pct < 40
  const barColor = isGood ? 'var(--color-accent-green)' : pct > 30 && pct < 70 ? 'var(--color-accent-warning)' : 'var(--color-accent-danger)'
  const prev = history.length > 1 ? (history[history.length - 2][config.key] as number) : null
  const delta = prev !== null ? value - prev : null
  const deltaGood = delta !== null ? (config.higherIsBetter ? delta > 0 : delta < 0) : null

  return (
    <motion.div
      className="rounded-lg p-2.5 group cursor-pointer"
      style={{
        background: 'var(--color-bg-panel)',
        border: '1px solid var(--color-border-subtle)',
        boxShadow: 'var(--shadow-sm)',
        transition: 'box-shadow 0.15s',
      }}
      whileHover={{ boxShadow: 'var(--shadow-md)' }}
    >
      {/* Top row */}
      <div className="flex justify-between items-start mb-1.5">
        <div className="flex-1 min-w-0">
          <span className="font-display text-[10px] font-medium" style={{ color: 'var(--color-text-secondary)' }}>
            {config.label}
          </span>
          {config.unit && (
            <span className="font-mono text-[9px] ml-1" style={{ color: 'var(--color-text-muted)' }}>
              {config.unit}
            </span>
          )}
        </div>
        <div className="flex items-center gap-1.5 shrink-0 ml-2">
          {delta !== null && Math.abs(delta) > 0.001 && (
            <span
              className="font-mono text-[9px]"
              style={{ color: deltaGood ? 'var(--color-accent-green)' : 'var(--color-accent-danger)' }}
            >
              {delta > 0 ? '▲' : '▼'}
            </span>
          )}
          <span className="font-mono text-[11px] font-bold" style={{ color: 'var(--color-text-primary)' }}>
            {config.format(value)}
          </span>
          <button
            onClick={(e) => { e.stopPropagation(); onExpand() }}
            className="w-5 h-5 flex items-center justify-center rounded opacity-0 group-hover:opacity-100 transition-opacity"
            style={{ border: '1px solid var(--color-border-subtle)', color: 'var(--color-text-muted)', background: 'var(--color-bg-panel)', boxShadow: 'var(--shadow-sm)' }}
            title={`Expand ${config.label}`}
          >
            <Maximize2 size={9} />
          </button>
        </div>
      </div>

      {/* Bar */}
      <div className="h-1 rounded-full overflow-hidden mb-1.5" style={{ background: 'var(--color-bg-hover)', boxShadow: 'var(--shadow-inset)' }}>
        <motion.div
          className="h-full rounded-full"
          style={{ background: barColor, boxShadow: `0 0 3px ${barColor}` }}
          animate={{ width: `${pct}%` }}
          transition={{ duration: 0.5, ease: 'easeOut' }}
        />
      </div>

      {/* Sparkline */}
      {history.length >= 3 && (
        <div style={{ height: 24, marginTop: 2 }}>
          <Sparkline history={history} config={config} color={color} height={24} />
        </div>
      )}
    </motion.div>
  )
}

// ─── Health gauge (unchanged) ────────────────────────────────────────────────

function HealthGauge({ value }: { value: number }) {
  const color = value > 70 ? 'var(--color-accent-green)' : value > 50 ? 'var(--color-accent-warning)' : 'var(--color-accent-danger)'
  const angle = -135 + (value / 100) * 270

  return (
    <div className="flex flex-col items-center py-2">
      <div className="relative w-24 h-14 overflow-hidden">
        <svg viewBox="0 0 100 60" className="w-full h-full">
          <path d="M 10 55 A 40 40 0 0 1 90 55" fill="none" stroke="var(--color-bg-hover)" strokeWidth="8" strokeLinecap="round" />
          <motion.path
            d="M 10 55 A 40 40 0 0 1 90 55"
            fill="none"
            stroke={color}
            strokeWidth="8"
            strokeLinecap="round"
            strokeDasharray="125.7"
            strokeDashoffset={125.7}
            animate={{ strokeDashoffset: 125.7 - (value / 100) * 125.7 }}
            transition={{ duration: 0.6, ease: 'easeOut' }}
            style={{ filter: `drop-shadow(0 0 4px ${color})` }}
          />
          <line
            x1="50" y1="55"
            x2={50 + 28 * Math.cos((angle - 90) * Math.PI / 180)}
            y2={55 + 28 * Math.sin((angle - 90) * Math.PI / 180)}
            stroke={color} strokeWidth="2" strokeLinecap="round"
          />
          <circle cx="50" cy="55" r="3" fill={color} />
        </svg>
      </div>
      <div className="text-center -mt-1">
        <motion.div
          key={Math.round(value)}
          initial={{ opacity: 0.5, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          className="font-mono font-bold text-2xl"
          style={{ color }}
        >
          {value.toFixed(0)}
        </motion.div>
        <div className="font-mono text-[9px] tracking-widest uppercase" style={{ color: 'var(--color-text-muted)' }}>
          City Health Score
        </div>
      </div>
    </div>
  )
}

// ─── Main dashboard ──────────────────────────────────────────────────────────

export function MetricsDashboard() {
  const [activeCategory, setActiveCategory] = useState<Category | 'all'>('all')
  const [expandedKey, setExpandedKey] = useState<string | null>(null)
  const [showScoreHelp, setShowScoreHelp] = useState(false)
  const [showAdvanced, setShowAdvanced] = useState(false)
  const metricsHistory = useSimulationStore((state) => state.metricsHistory)
  const planning = useSimulationStore((state) => state.planning)
  const currentMetrics = metricsHistory.at(-1) ?? null

  const mainMetricKeys = new Set(['mobility_transit_coverage', 'equity_hosp_coverage', 'econ_housing_afford', 'env_green_ratio', 'mobility_commute', 'env_co2_est'])
  const visibleMetrics = METRIC_CONFIGS.filter((m) => {
    const categoryMatch = activeCategory === 'all' || m.category === activeCategory
    return categoryMatch && (showAdvanced || mainMetricKeys.has(String(m.key)))
  })

  const expandedConfig = expandedKey ? METRIC_CONFIGS.find((c) => String(c.key) === expandedKey) ?? null : null
  const expandedColor = expandedConfig ? CATEGORY_COLORS[expandedConfig.category as Category] ?? 'var(--color-accent-cyan)' : 'var(--color-accent-cyan)'

  const handleExpand = useCallback((key: string) => setExpandedKey(key), [])
  const handleClose = useCallback(() => setExpandedKey(null), [])

  return (
    <>
      <div className="p-3 space-y-3">
        {/* Category filter */}
        <div className="flex items-center justify-between">
          <div className="font-mono text-[9px] tracking-widest uppercase" style={{ color: 'var(--color-text-muted)' }}>
            {showAdvanced ? 'Advanced Metrics' : 'Demo Metrics'}
          </div>
          <button
            onClick={() => setShowAdvanced((value) => !value)}
            className="px-2 py-1 rounded-md text-[10px] font-display"
            style={{ border: '1px solid var(--color-border-subtle)', color: 'var(--color-accent-cyan)', background: 'var(--color-bg-hover)' }}
          >
            {showAdvanced ? 'Show Core' : 'Advanced Metrics'}
          </button>
        </div>

        {/* Category filter */}
        {planning.beforeScores && (
          <div
            className="rounded-lg p-3"
            style={{ background: 'var(--color-bg-hover)', border: '1px solid var(--color-border-subtle)' }}
          >
            <div className="flex items-center justify-between mb-2">
              <div className="font-mono text-[9px] tracking-widest uppercase" style={{ color: 'var(--color-accent-cyan)' }}>
                Before Plan / After AI Plan
              </div>
              <button onClick={() => setShowScoreHelp(true)} title="How scores are calculated" style={{ color: 'var(--color-text-muted)' }}>
                <Info size={12} />
              </button>
            </div>
            <div className="grid grid-cols-2 gap-2 mb-2">
              <ScoreTile label="Current City Health" value={planning.beforeScores.cityHealth} />
              <ScoreTile label="New City Health" value={planning.afterScores?.cityHealth ?? planning.beforeScores.cityHealth} active={Boolean(planning.afterScores)} />
            </div>
            <div className="space-y-1">
              {planning.afterScores ? (
                <>
                  <Delta label="Emergency Access" before={planning.beforeScores.emergencyAccess} after={planning.afterScores.emergencyAccess} />
                  <Delta label="Transit Coverage" before={planning.beforeScores.transitCoverage} after={planning.afterScores.transitCoverage} />
                  <Delta label="Green Space" before={planning.beforeScores.greenSpace} after={planning.afterScores.greenSpace} />
                  <Delta label="Average Commute" before={planning.beforeScores.averageCommute} after={planning.afterScores.averageCommute} inverse suffix=" min" />
                  <Delta label="CO2 Estimate" before={planning.beforeScores.co2Estimate} after={planning.afterScores.co2Estimate} inverse suffix=" kt" />
                  <Delta label="Equity Score" before={planning.beforeScores.equityScore} after={planning.afterScores.equityScore} />
                </>
              ) : (
                <div className="font-mono text-[9px]" style={{ color: 'var(--color-text-muted)' }}>Apply the AI plan to compare score deltas.</div>
              )}
            </div>
          </div>
        )}

        {/* Category filter */}
        <div className="flex flex-wrap gap-1">
          <motion.button
            onClick={() => setActiveCategory('all')}
            whileHover={{ scale: 1.03 }}
            whileTap={{ scale: 0.97 }}
            className="px-2 py-0.5 rounded-md text-[10px] font-display transition-all"
            style={
              activeCategory === 'all'
                ? { background: 'var(--color-bg-hover)', color: 'var(--color-text-primary)', border: '1px solid var(--color-border-subtle)', boxShadow: 'var(--shadow-pressed)' }
                : { color: 'var(--color-text-muted)', border: '1px solid var(--color-border-subtle)', boxShadow: 'var(--shadow-sm)' }
            }
          >
            All
          </motion.button>
          {CATEGORIES.map((cat) => (
            <motion.button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              whileHover={{ scale: 1.03 }}
              whileTap={{ scale: 0.97 }}
              className="px-2 py-0.5 rounded-md text-[10px] font-display capitalize transition-all"
              style={
                activeCategory === cat
                  ? { background: 'var(--color-bg-hover)', color: CATEGORY_COLORS[cat], border: `1px solid ${CATEGORY_COLORS[cat]}50`, boxShadow: 'var(--shadow-pressed)' }
                  : { color: 'var(--color-text-muted)', border: '1px solid var(--color-border-subtle)', boxShadow: 'var(--shadow-sm)' }
              }
            >
              {cat}
            </motion.button>
          ))}
        </div>

        {!currentMetrics ? (
          <div
            className="rounded-xl p-6 text-center space-y-2"
            style={{ background: 'var(--color-bg-hover)', border: '1px dashed var(--color-border-subtle)', boxShadow: 'var(--shadow-inset)' }}
          >
            <div className="font-mono text-[10px] tracking-widest uppercase" style={{ color: 'var(--color-text-muted)' }}>
              No Data Yet
            </div>
            <div className="font-mono text-[9px]" style={{ color: 'var(--color-text-muted)' }}>
              Start the simulation to see live metrics, charts, and trends across all categories.
            </div>
          </div>
        ) : (
          <>
            <HealthGauge value={computeHealth(currentMetrics)} />

            <div className="space-y-1.5">
              {visibleMetrics.map((config) => (
                <MetricRow
                  key={String(config.key)}
                  config={config}
                  metrics={currentMetrics}
                  history={metricsHistory}
                  color={CATEGORY_COLORS[config.category as Category] ?? 'var(--color-accent-cyan)'}
                  onExpand={() => handleExpand(String(config.key))}
                />
              ))}
            </div>

            {/* Hint for expand */}
            <div
              className="text-center font-mono text-[9px] tracking-widest"
              style={{ color: 'var(--color-text-muted)' }}
            >
              Hover a metric and click
              <Maximize2 size={8} className="inline mx-1" style={{ verticalAlign: 'middle' }} />
              to expand
            </div>
          </>
        )}
      </div>

      {/* Expanded modal — portal escapes sidebar transform context */}
      {createPortal(
        <AnimatePresence>
          {expandedConfig && (
            <ExpandedModal
              config={expandedConfig}
              history={metricsHistory}
              color={expandedColor}
              onClose={handleClose}
            />
          )}
        </AnimatePresence>,
        document.body
      )}
      {createPortal(
        <AnimatePresence>
          {showScoreHelp && (
            <ScoreHelpModal onClose={() => setShowScoreHelp(false)} />
          )}
        </AnimatePresence>,
        document.body
      )}
    </>
  )
}

function ScoreTile({ label, value, active = false }: { label: string; value: number; active?: boolean }) {
  return (
    <div className="rounded-lg p-2 text-center" style={{ background: active ? 'rgba(0,184,148,0.08)' : 'var(--color-bg-card)', border: active ? '1px solid rgba(0,184,148,0.35)' : '1px solid var(--color-border-subtle)' }}>
      <div className="font-mono font-bold text-lg" style={{ color: active ? 'var(--color-accent-green)' : 'var(--color-text-primary)' }}>{value}</div>
      <div className="font-mono text-[8px] tracking-widest uppercase" style={{ color: 'var(--color-text-muted)' }}>{label}</div>
    </div>
  )
}

function Delta({ label, before, after, inverse = false, suffix = '' }: { label: string; before: number; after: number; inverse?: boolean; suffix?: string }) {
  const delta = Math.round((after - before) * 10) / 10
  const good = inverse ? delta < 0 : delta > 0
  return (
    <div className="flex items-center justify-between font-mono text-[9px]">
      <span style={{ color: 'var(--color-text-muted)' }}>{label}</span>
      <span style={{ color: good ? 'var(--color-accent-green)' : delta === 0 ? 'var(--color-text-muted)' : 'var(--color-accent-danger)' }}>
        {delta > 0 ? '+' : ''}{delta}{suffix}
      </span>
    </div>
  )
}

function ScoreHelpModal({ onClose }: { onClose: () => void }) {
  return (
    <motion.div className="fixed inset-0 z-50 flex items-center justify-center p-6" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} style={{ background: 'rgba(0,0,0,0.72)', backdropFilter: 'blur(6px)' }} onClick={onClose}>
      <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 12 }} className="p-5" style={{ width: 520, maxWidth: '94vw', background: 'var(--color-bg-panel)', border: '1px solid var(--color-border-subtle)', borderRadius: 10 }} onClick={(e) => e.stopPropagation()}>
        <div className="flex justify-between items-center mb-3">
          <h3 className="font-display font-semibold text-sm" style={{ color: 'var(--color-text-primary)' }}>How Scores Are Calculated</h3>
          <button onClick={onClose} style={{ color: 'var(--color-text-muted)' }}><X size={14} /></button>
        </div>
        <p className="text-[11px] leading-relaxed mb-3" style={{ color: 'var(--color-text-secondary)' }}>
          UrbanMind uses deterministic local scenario scoring for this demo. The formulas estimate access and pressure from seeded infrastructure, underserved zones, and the selected growth scenario. Real spatial calculations can replace these functions later.
        </p>
        <div className="font-mono text-[10px] leading-relaxed" style={{ color: 'var(--color-text-muted)' }}>
          City Health = Transit Coverage 25% + Emergency Access 20% + Housing Access 20% + Walkability 15% + Green Space 10% + Congestion 10%. Emergency, transit, and green-space scores estimate zone coverage within practical service radii. Equity estimates whether gaps are concentrated or distributed.
        </div>
      </motion.div>
    </motion.div>
  )
}
